---
name: Push to Main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  echo:
    name: Test var substitution
    uses: ./.github/workflows/_echo-value.yaml
    with:
      thing-to-echo: --set=metabase.dbMigrations.env.dbUrl=postgres://metabase:$$(DB_PASSWORD)@metabase-db/metabase?search_path=metabase&sslmode=disable