---
name: Push to Main
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  echo:
    name: Test var substitution
    uses: ./.github/workflows/_echo-value.yaml
    with:
      thing-to-echo: --set=metabase.env.xUrl=metabase:$$(SOMETHING)@metabase-db/metabase?search_path=metabase&sslmode=disable