---
name: Push to Main
on:
  workflow_dispatch:
    inputs:
      someValue:
        description: 'Test value'
        default: metabase:$$(XY_NAME)@somewhere
  push:
    branches:
      - main

jobs:
  test:
    name: Test var substitution
    runs-on: ubuntu-latest
    steps:
      - name: Echo the value
        run: |
          echo "Value: ${{ inputs.someValue }}"